//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundamentalBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TransactionDetails
    {
        public int TransactionId { get; set; }
        public string SourceAccNum { get; set; }
        public string DestinationAccNum { get; set; }
        public Nullable<decimal> Amounttransacted { get; set; }
        public string Typeoftransaction { get; set; }
        public Nullable<System.DateTime> Dateoftransaction { get; set; }
    }
}
