//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundamentalBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Customer_Details()
        {
            this.tbl_Customer_Account_Details = new HashSet<tbl_Customer_Account_Details>();
        }
    
        public long CustomerID { get; set; }
        public string CustomerName { get; set; }
        public long SSN_ID { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public int StateID { get; set; }
        public int CityID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Customer_Account_Details> tbl_Customer_Account_Details { get; set; }
    }
}
