//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundamentalBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer_Account_Details
    {
        public long CustomerId { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
    
        public virtual tbl_Customer_Details tbl_Customer_Details { get; set; }
    }
}
